version: '3.4'
services:
  dockordbot:
    image: ${DOCKER_REGISTRY-}dockordbot
    build:
      context: .
      dockerfile: Dockord.Bot/Dockerfile
 
  seq:
    container_name: Dockord.Seq
    image: datalust/seq:latest