version: '3.4'
services:
  dockordbot:
    image: ${DOCKER_REGISTRY-}dockordbot.tests
    build:
      context: .
      dockerfile: Unittests.Dockerfile
      target: tests
    environment:
      - DOTNET_ENVIRONMENT=Development
      - Serilog__MinimumLevel__Default=Debug
      - Serilog__SeqUrl=http://seq
      - BotSettings__AlwaysCacheMembers=true
      - BotSettings__ErrorMessageDeleteSecondsDelay=5
      - BotSettings__MessageCacheSize=1024
      - BotSettings__Prefix=!
      - BotSettings__Token=